[2024-11-28T11:29:35.408+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-28T11:29:35.417+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: football_data.write_data manual__2024-11-28T11:29:23.665507+00:00 [queued]>
[2024-11-28T11:29:35.423+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: football_data.write_data manual__2024-11-28T11:29:23.665507+00:00 [queued]>
[2024-11-28T11:29:35.423+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-28T11:29:35.442+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): write_data> on 2024-11-28 11:29:23.665507+00:00
[2024-11-28T11:29:35.448+0000] {standard_task_runner.py:72} INFO - Started process 7721 to run task
[2024-11-28T11:29:35.452+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'football_data', 'write_data', 'manual__2024-11-28T11:29:23.665507+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/football_dag.py', '--cfg-path', '/tmp/tmp17jtzo6z']
[2024-11-28T11:29:35.455+0000] {standard_task_runner.py:105} INFO - Job 141: Subtask write_data
[2024-11-28T11:29:35.494+0000] {task_command.py:467} INFO - Running <TaskInstance: football_data.write_data manual__2024-11-28T11:29:23.665507+00:00 [running]> on host ip-172-31-28-221.eu-north-1.compute.internal
[2024-11-28T11:29:35.559+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='aman Singh' AIRFLOW_CTX_DAG_ID='football_data' AIRFLOW_CTX_TASK_ID='write_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T11:29:23.665507+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-28T11:29:23.665507+00:00'
[2024-11-28T11:29:35.560+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-28T11:29:35.592+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow/pipelines/extraction_data.py", line 110, in writing_data
    filename =local_file_path/{file_path},
             ~~~~~~~~~~~~~~~^~~~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'str' and 'set'
[2024-11-28T11:29:35.599+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=football_data, task_id=write_data, run_id=manual__2024-11-28T11:29:23.665507+00:00, execution_date=20241128T112923, start_date=20241128T112935, end_date=20241128T112935
[2024-11-28T11:29:35.615+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-28T11:29:35.616+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 141 for task write_data (unsupported operand type(s) for /: 'str' and 'set'; 7721)
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow/pipelines/extraction_data.py", line 110, in writing_data
    filename =local_file_path/{file_path},
             ~~~~~~~~~~~~~~~^~~~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'str' and 'set'
[2024-11-28T11:29:35.666+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-28T11:29:35.677+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-28T11:29:35.677+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
